version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/core-admin"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/core-auth0-actions"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/web-admin"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
