version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/core"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/web-client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
