name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        docker build -t techno-event-management-core .

    - run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - run: |
        docker tag techno-event-management-core ${{ secrets.DOCKER_USER }}/techno-event-management-core:latest
        docker push ${{ secrets.DOCKER_USER }}/techno-event-management-core:latest
    
  redeploy-backend:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Call deploy hook
      run: |
        curl -X GET ${{ secrets.BACKEND_DEPLOY_HOOK }}
