name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-core-admin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          docker build -t techno-event-core-admin -f apps/core-admin/Dockerfile .

      - run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker tag techno-event-core-admin ${{ secrets.DOCKER_USER }}/techno-event-core-admin:latest
          docker push ${{ secrets.DOCKER_USER }}/techno-event-core-admin:latest

  redeploy-core-admin:
    needs: build-and-push-core-admin
    runs-on: ubuntu-latest
    steps:
      - name: Call deploy hook
        run: |
          curl -X GET ${{ secrets.DEV_CORE_ADMIN_DEPLOY_HOOK }}
          curl -X GET ${{ secrets.PROD_CORE_ADMIN_DEPLOY_HOOK }}
          
  build-and-push-core-auth0-actions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          docker build -t techno-event-core-auth0-actions -f apps/core-auth0-actions/Dockerfile .

      - run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker tag techno-event-core-auth0-actions ${{ secrets.DOCKER_USER }}/techno-event-core-auth0-actions:latest
          docker push ${{ secrets.DOCKER_USER }}/techno-event-core-auth0-actions:latest

  redeploy-core-auth0-actions:
    needs: build-and-push-core-auth0-actions
    runs-on: ubuntu-latest
    steps:
      - name: Call deploy hook
        run: |
          curl -X GET ${{ secrets.DEV_CORE_AUTH0_ACTIONS_DEPLOY_HOOK }}
          curl -X GET ${{ secrets.PROD_CORE_AUTH0_ACTIONS_DEPLOY_HOOK }}
